//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.DAL.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBranch
    {
        public tblBranch()
        {
            this.tblClasses = new HashSet<tblClass>();
            this.tblDepartments = new HashSet<tblDepartment>();
        }
    
        public int Id { get; set; }
        public string BranchName { get; set; }
        public string BranchCode { get; set; }
        public Nullable<int> BranchHeadID { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual ICollection<tblClass> tblClasses { get; set; }
        public virtual ICollection<tblDepartment> tblDepartments { get; set; }
    }
}
