//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.DAL.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartment
    {
        public tblDepartment()
        {
            this.tblClasses = new HashSet<tblClass>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> DepHeadId { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual tblBranch tblBranch { get; set; }
        public virtual ICollection<tblClass> tblClasses { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
