//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.DAL.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblBranches = new HashSet<tblBranch>();
            this.tblDepartments = new HashSet<tblDepartment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> UserTypeId { get; set; }
    
        public virtual ICollection<tblBranch> tblBranches { get; set; }
        public virtual ICollection<tblDepartment> tblDepartments { get; set; }
        public virtual tblUserType tblUserType { get; set; }
    }
}
